### ISSUE TITLE
Green version

### ISSUE THREAD

**Issue by tbremer** [SebastianSzturo/firewatch-syntax#3]
Would you be open to a green dominate version of the scheme?

Campo Santo released a similar wallpaper:
![firewatch green](http://67.media.tumblr.com/85ac3c19f74c65386969162b12e24f46/tumblr_inline_o29dnbbdq41rtb73a_500.jpg)

Will happily make a pull request.

**Comment by SebastianSzturo** [comment]
Really great idea! So unfortunately it's not possible to have settings for syntax themes. We probably need to push a second theme. I forked the red theme [here](https://github.com/SebastianSzturo/firewatch-green-syntax). If you want, you can open a pr and add the green colors, otherwise I will look into it on the weekend! 🚀

**Comment by SebastianSzturo** [comment]
🚢 https://atom.io/themes/firewatch-green-syntax
